name = "087b0e74d9f542d2ad9b-sync-kelowna-shows"
main = "index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = [ "0 14 * * *" ]

[observability]
enabled = true

  [observability.logs]
  enabled = true
  invocation_logs = true

[cors_headers]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Max-Age = "86400"
